name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app
        run: |
          python app2.py &
        env:
          FLASK_APP: app2.py
          FLASK_ENV: development

      - name: Install WebDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo apt-get install -y \
           libnss3 \
           libgconf-2-4 \
           libx11-xcb1 \
           libgdk-pixbuf2.0-0 \
           libasound2 \
           fonts-liberation \
           libappindicator3-1 \
           libatk-bridge2.0-0 \
           libatk1.0-0 \
           libxcb-dri3-0 \
           libdbus-glib-1-2 \
           libnspr4 \
           libxss1 \
           xdg-utils
          #sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Run tests
        run: pytest
